/********************************************************************************
STEP 5: MAGNITUDE ANALYSIS

Goal:
Compare key business measures (like revenue, cost, quantity) across categories 
such as country, gender, product, and customer to identify high-performing segments.

Data Sources:
- gold.dim_customers
- gold.dim_products
- gold.fact_sales
*********************************************************************************/


-- Find total customers by country
-- Here, customer_key is already distinct
SELECT
    country,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country;
GO


-- Find total customers by gender
SELECT
    gender,
    COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender;
GO


-- Find total products by category
-- Try to filter out first before any aggregation
SELECT
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
WHERE category IS NOT NULL
GROUP BY category
ORDER BY total_products DESC;
GO


-- What is the average cost in each category?
SELECT
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
WHERE category IS NOT NULL
GROUP BY category
ORDER BY avg_cost DESC;
GO


-- What is the total revenue generated for each category?
-- You can also use subcategory.
SELECT
    p.category,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
    ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;
GO


-- What is the total revenue generated by each customer?
SELECT
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;
GO


-- What is the total revenue generated by each country?
SELECT
    c.country,
    SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_revenue DESC;
GO


-- What is the distribution of sold items across countries?
SELECT
    c.country,
    SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
    ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;
GO
